[package]
name = "kern-enforcer"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kern-core = { path = "../kern-core", default-features = false }
ed25519-dalek = { version = "2", default-features = false }

[features]
default = ["std"]
std = ["kern-core/std", "ed25519-dalek/std"]

[dev-dependencies]
kern-authority = { path = "../kern-authority" }
kern-policy = { path = "../kern-policy" }
