#!/usr/bin/env python3
"""Generates kern_corridor.pgm from the same numbers as kern_corridor.sdf.

The occupancy map and the simulated world must agree. They disagreed once —
the SDF corridor walls left a 0.2 m gap where the map said 2 m, and Nav2
planned happily through a wall the robot then drove into — so the geometry
lives here, in one place, and the map is regenerated rather than hand-edited.

    python3 generate_map.py

World frame: 20 m x 10 m centred on the origin. Map frame: the PGM's lower-left
corner is world (-10, -5) at 0.05 m/px, which is what kern_corridor.yaml
declares as its origin.
"""

RESOLUTION = 0.05
WIDTH_M, HEIGHT_M = 20.0, 10.0
WALL_T = 0.2
#: The clear lane, in world y. Wide enough for the robot plus inflation plus
#: the two obstacles that sit inside it.
LANE_HALF_WIDTH = 1.5
#: Corridor walls, in world x.
CORRIDOR_X = (-5.9, 2.1)
#: Obstacles, as world (x_min, y_min, x_max, y_max).
OBSTACLES = [(-3.0, -0.8, -2.4, -0.2), (-0.5, 0.2, 0.1, 0.8)]

WIDTH = int(WIDTH_M / RESOLUTION)
HEIGHT = int(HEIGHT_M / RESOLUTION)
FREE, OCCUPIED = 254, 0


def main():
    grid = [[FREE] * WIDTH for _ in range(HEIGHT)]

    def fill(x0, y0, x1, y1):
        """Marks a world-frame rectangle occupied."""
        gx0 = max(0, int((x0 + WIDTH_M / 2) / RESOLUTION))
        gx1 = min(WIDTH, int((x1 + WIDTH_M / 2) / RESOLUTION))
        gy0 = max(0, int((y0 + HEIGHT_M / 2) / RESOLUTION))
        gy1 = min(HEIGHT, int((y1 + HEIGHT_M / 2) / RESOLUTION))
        for gy in range(gy0, gy1):
            for gx in range(gx0, gx1):
                grid[HEIGHT - 1 - gy][gx] = OCCUPIED  # PGM rows run top-down

    half_w, half_h = WIDTH_M / 2, HEIGHT_M / 2
    fill(-half_w, -half_h, half_w, -half_h + WALL_T)          # south
    fill(-half_w, half_h - WALL_T, half_w, half_h)            # north
    fill(-half_w, -half_h, -half_w + WALL_T, half_h)          # west
    fill(half_w - WALL_T, -half_h, half_w, half_h)            # east

    for x in CORRIDOR_X:
        fill(x, -half_h, x + WALL_T, -LANE_HALF_WIDTH)
        fill(x, LANE_HALF_WIDTH, x + WALL_T, half_h)

    for x0, y0, x1, y1 in OBSTACLES:
        fill(x0, y0, x1, y1)

    path = __file__.rsplit("/", 1)[0] + "/kern_corridor.pgm"
    with open(path, "wb") as out:
        out.write(b"P5\n# Kern Phase 6 corridor, generated by generate_map.py\n")
        out.write(b"%d %d\n255\n" % (WIDTH, HEIGHT))
        out.write(bytes(v for row in grid for v in row))
    print(f"wrote {path}: {WIDTH} x {HEIGHT} px, lane +/-{LANE_HALF_WIDTH} m")


if __name__ == "__main__":
    main()
