[package]
name = "kern-authority"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
kern-core = { path = "../kern-core", default-features = false }
kern-policy = { path = "../kern-policy", default-features = false }
ed25519-dalek = { version = "2", default-features = false }

[features]
default = ["std"]
std = ["kern-core/std", "kern-policy/std", "ed25519-dalek/std"]

[dev-dependencies]
ed25519-dalek = "2"
